export const REASON_CODES = {
  STRONG_DIRECTIONAL_MOMENTUM: "STRONG_DIRECTIONAL_MOMENTUM",
  TECHNICAL_CONFLUENCE_SUPPORTIVE: "TECHNICAL_CONFLUENCE_SUPPORTIVE",
  RELATIVE_OPPORTUNITY_WINNER: "RELATIVE_OPPORTUNITY_WINNER",
  MARKET_ALIGNMENT_SUPPORTIVE: "MARKET_ALIGNMENT_SUPPORTIVE",
  INSUFFICIENT_DIRECTIONAL_EVIDENCE: "INSUFFICIENT_DIRECTIONAL_EVIDENCE",
  HIGH_EVIDENCE_CONFLICT: "HIGH_EVIDENCE_CONFLICT",
  INSUFFICIENT_COVERAGE: "INSUFFICIENT_COVERAGE",
  REQUIRED_EVIDENCE_UNAVAILABLE: "REQUIRED_EVIDENCE_UNAVAILABLE",
  EXTREME_VOLATILITY: "EXTREME_VOLATILITY",
  REQUIRED_RISK_UNKNOWN: "REQUIRED_RISK_UNKNOWN",
  REGIME_MISMATCH: "REGIME_MISMATCH",
  REGIME_UNKNOWN: "REGIME_UNKNOWN",
  SAFETY_VETO: "SAFETY_VETO",
  SAFETY_EVIDENCE_UNAVAILABLE: "SAFETY_EVIDENCE_UNAVAILABLE",
  NO_CLEAR_RELATIVE_WINNER: "NO_CLEAR_RELATIVE_WINNER",
  NARRATIVE_OVERHEATING: "NARRATIVE_OVERHEATING",
  NARRATIVE_CONTRADICTION: "NARRATIVE_CONTRADICTION",
  FRAGILE_EVIDENCE_BASE: "FRAGILE_EVIDENCE_BASE",
} as const;

export type ReasonCode =
  (typeof REASON_CODES)[keyof typeof REASON_CODES];

export const WARNING_CODES = {
  ELEVATED_RISK: "ELEVATED_RISK",
  MODERATE_EVIDENCE_CONFLICT: "MODERATE_EVIDENCE_CONFLICT",
  DEGRADED_REGIME_FIT: "DEGRADED_REGIME_FIT",
} as const;

export type WarningCode =
  (typeof WARNING_CODES)[keyof typeof WARNING_CODES];
